#ifndef version_hh
#define version_hh

#define PACMAN_SERVER_MAJOR_VERSION 2
#define PACMAN_SERVER_MINOR_VERSION 5

#define PACMAN_FW_MAJOR_VERSION_TARGET 2
#define PACMAN_FW_MINOR_VERSION_MINIMUM 0
#define PACMAN_FW_MINOR_VERSION_MAXIMUM 0

#endif
